[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
venv = "venv"
pythonVersion = "3.12"
ignore = ["src\\hanual\\lang\\builtin_parser.py"]
