name=""
entery=""

[preprocessers]
prefix='@'
nif='nif'
end='end'
def='def'
if='if'

[predefs]
predefinitions=[]

[packets]

[warnif]
macrosubstitution=false
shoutkw=false

[target]
target='bundle'
packall=false
